---
apiVersion: v1
kind: Service
metadata:
  name: pluginservice
  labels:
    app: pluginservice
spec:
  ports:
  - name: {{ .Values.service.name }}
    port: {{ .Values.service.externalPort }}
    protocol: TCP
    targetPort: {{ .Values.service.internalPort }}
  selector:
    app: pluginservice
  type: ClusterIP  
