---
apiVersion: v1
kind: Service
metadata:
  name: easytravel-frontend
  labels:
    app: easytravel-frontend
spec:
  ports:
  - name: {{ .Values.service.name }}
    port: {{ .Values.service.externalPort }}
    protocol: TCP
    targetPort: {{ .Values.service.internalPort }}
  - name: rest  
    port: 8091
    protocol: TCP
    targetPort: 8091    
  selector:
    app: easytravel-frontend
  type: ClusterIP
